---@diagnostic disable:undefined-global

smm_compat.itemstring = {}
if smm_compat.mtg_available then
    -- Tools and weapons
    smm_compat.itemstring.bucket = "bucket:bucket_empty"
    smm_compat.itemstring.bucket_water = "bucket:bucket_water"
    smm_compat.itemstring.bucket_river_water = "bucket:bucket_river_water"
    smm_compat.itemstring.bucket_lava = "bucket:bucket_lava"

    -- Ores, Minerals, Ingots
    smm_compat.itemstring.clay = "default:clay_lump"
    smm_compat.itemstring.clay_block = "default:clay"
    smm_compat.itemstring.brick = "default:clay_brick"
    smm_compat.itemstring.brick_block = "default:brick"
    smm_compat.itemstring.coal = "default:coal_lump"
    smm_compat.itemstring.coal_block = "default:coalblock"
    smm_compat.itemstring.raw_copper = "default:copper_lump"
    smm_compat.itemstring.copper_ingot = "default:copper_ingot"
    smm_compat.itemstring.copper_block = "default:copperblock"
    smm_compat.itemstring.diamond = "default:diamond"
    smm_compat.itemstring.diamond_block = "default:diamondblock"
    smm_compat.itemstring.raw_gold = "default:gold_lump"
    smm_compat.itemstring.gold_ingot = "default:gold_ingot"
    smm_compat.itemstring.gold_block = "default:goldblock"
    smm_compat.itemstring.raw_iron = "default:iron_lump"
    smm_compat.itemstring.iron_ingot = "default:steel_ingot"
    smm_compat.itemstring.iron_block = "default:steelblock"
    smm_compat.itemstring.redstone = "default:mese_crystal_fragment"
    smm_compat.itemstring.redstone_block = "default:mese_crystal"
    smm_compat.itemstring.obsidian = "default:obsidian"
    smm_compat.itemstring.raw_tin = "default:tin_lump"
    smm_compat.itemstring.tin_ingot = "default:tin_ingot"
    smm_compat.itemstring.tin_block = "default:tinblock"
    smm_compat.itemstring.bronze_ingot = "default:bronze_ingot"
    smm_compat.itemstring.bronze_block = "default:bronzeblock"

    -- Dye
    smm_compat.itemstring.dye_white = "dye:white"
    smm_compat.itemstring.dye_light_grey = "dye:grey"
    smm_compat.itemstring.dye_grey = "dye:dark_grey"
    smm_compat.itemstring.dye_black = "dye:black"
    smm_compat.itemstring.dye_blue = "dye:blue"
    smm_compat.itemstring.dye_cyan = "dye:cyan"
    smm_compat.itemstring.dye_lime = "dye:green"
    smm_compat.itemstring.dye_green = "dye:dark_green"
    smm_compat.itemstring.dye_yellow = "dye:yellow"
    smm_compat.itemstring.dye_orange = "dye:orange"
    smm_compat.itemstring.dye_brown = "dye:brown"
    smm_compat.itemstring.dye_red = "dye:red"
    smm_compat.itemstring.dye_pink = "dye:pink"
    smm_compat.itemstring.dye_magenta = "dye:magenta"
    smm_compat.itemstring.dye_purple = "dye:violet"

    -- Wool
    smm_compat.itemstring.wool_white = "wool:white"
    smm_compat.itemstring.wool_light_grey = "wool:grey"
    smm_compat.itemstring.wool_grey = "wool:dark_grey"
    smm_compat.itemstring.wool_black = "wool:black"
    smm_compat.itemstring.wool_blue = "wool:blue"
    smm_compat.itemstring.wool_cyan = "wool:cyan"
    smm_compat.itemstring.wool_lime = "wool:green"
    smm_compat.itemstring.wool_green = "wool:dark_green"
    smm_compat.itemstring.wool_yellow = "wool:yellow"
    smm_compat.itemstring.wool_orange = "wool:orange"
    smm_compat.itemstring.wool_brown = "wool:brown"
    smm_compat.itemstring.wool_red = "wool:red"
    smm_compat.itemstring.wool_pink = "wool:pink"
    smm_compat.itemstring.wool_magenta = "wool:magenta"
    smm_compat.itemstring.wool_purple = "wool:violet"

    -- Vegetation
    smm_compat.itemstring.cactus = "default:cactus"
    smm_compat.itemstring.sugar_cane = "default:papyrus"

    -- Terrain
    smm_compat.itemstring.snowball = "default:snow"
    smm_compat.itemstring.snow = "default:snowblock"
    smm_compat.itemstring.ice = "default:ice"
    smm_compat.itemstring.dirt = "default:dirt"
    smm_compat.itemstring.grass = "default:dirt_with_grass"
    smm_compat.itemstring.sand = "default:sand"
    smm_compat.itemstring.sandstone = "default:sandstone"
    smm_compat.itemstring.gravel = "default:gravel"
    smm_compat.itemstring.flint = "default:flint"
    smm_compat.itemstring.cobble = "default:cobble"
    smm_compat.itemstring.mossy_cobble = "default:mossycobble"
    smm_compat.itemstring.stone = "default:stone"

    -- Other
    smm_compat.itemstring.string = "farming:string"
    smm_compat.itemstring.gunpowder = "tnt:gunpowder"
    smm_compat.itemstring.tnt = "tnt:tnt"
    smm_compat.itemstring.stick = "default:stick"
    smm_compat.itemstring.paper = "default:paper"
    smm_compat.itemstring.torch = "default:torch"
    smm_compat.itemstring.flint_and_steel = "fire:flint_and_steel"
    smm_compat.itemstring.glass = "default:glass"
elseif smm_compat.mcl_available then
    -- Tools and weapons
    smm_compat.itemstring.bucket = "mcl_buckets:bucket_empty"
    smm_compat.itemstring.bucket_water = "mcl_buckets:bucket_water"
    smm_compat.itemstring.bucket_river_water = "mcl_buckets:bucket_river_water"
    smm_compat.itemstring.bucket_lava = "mcl_buckets:bucket_lava"

    -- Ores, Minerals, Ingots
    smm_compat.itemstring.clay = "mcl_core:clay_lump"
    smm_compat.itemstring.clay_block = "mcl_core:clay"
    smm_compat.itemstring.brick = "mcl_core:brick"
    smm_compat.itemstring.brick_block = "mcl_core:brick_block"
    smm_compat.itemstring.coal = "mcl_core:coal_lump"
    smm_compat.itemstring.coal_block = "mcl_core:coalblock"
    smm_compat.itemstring.raw_copper = "mcl_copper:raw_copper"
    smm_compat.itemstring.copper_ingot = "mcl_copper:copper_ingot"
    smm_compat.itemstring.copper_block = "mcl_copper:block"
    smm_compat.itemstring.diamond = "mcl_core:diamond"
    smm_compat.itemstring.diamond_block = "mcl_core:diamondblock"
    smm_compat.itemstring.raw_gold = "mcl_raw_ores:raw_gold"
    smm_compat.itemstring.gold_ingot = "mcl_core:gold_ingot"
    smm_compat.itemstring.gold_block = "mcl_core:goldblock"
    smm_compat.itemstring.raw_iron = "mcl_raw_ores:raw_iron"
    smm_compat.itemstring.iron_ingot = "mcl_core:iron_ingot"
    smm_compat.itemstring.iron_block = "mcl_core:ironblock"
    smm_compat.itemstring.redstone = "mesecons:redstone"
    smm_compat.itemstring.redstone_block = "mesecons_torch:redstoneblock"
    smm_compat.itemstring.obsidian = "mcl_core:obsidian"
    smm_compat.itemstring.raw_tin = "smm_material:raw_tin"
    smm_compat.itemstring.tin_ingot = "smm_material:tin_ingot"
    smm_compat.itemstring.tin_block = "smm_material:tinblock"
    smm_compat.itemstring.bronze_ingot = "smm_material:bronze_ingot"
    smm_compat.itemstring.bronze_block = "smm_material:bronzeblock"

    -- Dye
    smm_compat.itemstring.dye_white = "mcl_dyes:white"
    smm_compat.itemstring.dye_light_grey = "mcl_dyes:light_grey"
    smm_compat.itemstring.dye_grey = "mcl_dyes:grey"
    smm_compat.itemstring.dye_black = "mcl_dyes:black"
    smm_compat.itemstring.dye_light_blue = "mcl_dyes:light_blue"
    smm_compat.itemstring.dye_blue = "mcl_dyes:blue"
    smm_compat.itemstring.dye_cyan = "mcl_dyes:cyan"
    smm_compat.itemstring.dye_lime = "mcl_dyes:lime"
    smm_compat.itemstring.dye_green = "mcl_dyes:green"
    smm_compat.itemstring.dye_yellow = "mcl_dyes:yellow"
    smm_compat.itemstring.dye_orange = "mcl_dyes:orange"
    smm_compat.itemstring.dye_brown = "mcl_dyes:brown"
    smm_compat.itemstring.dye_red = "mcl_dyes:red"
    smm_compat.itemstring.dye_pink = "mcl_dyes:pink"
    smm_compat.itemstring.dye_magenta = "mcl_dyes:magenta"
    smm_compat.itemstring.dye_purple = "mcl_dyes:purple"

    -- Wool
    smm_compat.itemstring.wool_white = "mcl_wool:white"
    smm_compat.itemstring.wool_light_grey = "mcl_wool:light_grey"
    smm_compat.itemstring.wool_grey = "mcl_wool:grey"
    smm_compat.itemstring.wool_black = "mcl_wool:black"
    smm_compat.itemstring.wool_light_blue = "mcl_wool:light_blue"
    smm_compat.itemstring.wool_blue = "mcl_wool:blue"
    smm_compat.itemstring.wool_cyan = "mcl_wool:cyan"
    smm_compat.itemstring.wool_lime = "mcl_wool:lime"
    smm_compat.itemstring.wool_green = "mcl_wool:green"
    smm_compat.itemstring.wool_yellow = "mcl_wool:yellow"
    smm_compat.itemstring.wool_orange = "mcl_wool:orange"
    smm_compat.itemstring.wool_brown = "mcl_wool:brown"
    smm_compat.itemstring.wool_red = "mcl_wool:red"
    smm_compat.itemstring.wool_pink = "mcl_wool:pink"
    smm_compat.itemstring.wool_magenta = "mcl_wool:magenta"
    smm_compat.itemstring.wool_purple = "mcl_wool:purple"

    -- Vegetation
    smm_compat.itemstring.cactus = "mcl_core:cactus"
    smm_compat.itemstring.sugar_cane = "mcl_core:reeds"

    -- Terrain
    smm_compat.itemstring.snowball = "mcl_throwing:snowball"
    smm_compat.itemstring.snow = "mcl_core:snowblock"
    smm_compat.itemstring.ice = "mcl_core:ice"
    smm_compat.itemstring.dirt = "mcl_core:dirt"
    smm_compat.itemstring.grass = "mcl_core:dirt_with_grass"
    smm_compat.itemstring.sand = "mcl_core:sand"
    smm_compat.itemstring.sandstone = "mcl_core:sandstone"
    smm_compat.itemstring.gravel = "mcl_core:gravel"
    smm_compat.itemstring.flint = "mcl_core:flint"
    smm_compat.itemstring.cobble = "mcl_core:cobble"
    smm_compat.itemstring.mossy_cobble = "mcl_core:mossycobble"
    smm_compat.itemstring.deepslate_cobble = "mcl_deepslate:deepslate_cobbled"
    smm_compat.itemstring.stone = "mcl_core:stone"
    smm_compat.itemstring.deepslate = "mcl_deepslate:deepslate"
    smm_compat.itemstring.diorite = "mcl_core:diorite"
    smm_compat.itemstring.andesite = "mcl_core:andesite"
    smm_compat.itemstring.granite = "mcl_core:granite"
    smm_compat.itemstring.tuff = "mcl_deepslate:tuff"

    -- Other
    smm_compat.itemstring.string = "mcl_mobitems:string"
    smm_compat.itemstring.gunpowder = "mcl_mobitems:gunpowder"
    smm_compat.itemstring.tnt = "mcl_tnt:tnt"
    smm_compat.itemstring.stick = "mcl_core:stick"
    smm_compat.itemstring.paper = "mcl_core:paper"
    smm_compat.itemstring.torch = "mcl_torches:torch"
    smm_compat.itemstring.flint_and_steel = "mcl_fire:flint_and_steel"
    smm_compat.itemstring.glass = "mcl_core:glass"
end

-- Groups
smm_compat.itemstring.group_flammable = "group:flammable"
smm_compat.itemstring.group_sand = "group:sand"
smm_compat.itemstring.group_stone = "group:stone"
smm_compat.itemstring.group_log = "group:tree"
smm_compat.itemstring.group_plank = "group:wood"
smm_compat.itemstring.group_wool = "group:wool"
